### ISSUE TITLE
Purchasers are randomly redirected to empty order form

### ISSUE THREAD

**Issue by CorpulentBrony** [snowpity/concrescent#2]
Sometimes, after completing a purchase at PayPal, instead of seeing a successful payment message, the user is redirected to a blank badge order form.  A lot of users take this to mean there was a payment processing issue and make a duplicate order which we then need to refund.  

For customer service purposes, this should be a high priority issue.

**Comment by Wolvan** [comment]
Current assumption is that it has to do with either cookies being disabled or an adblocker

**Comment by CorpulentBrony** [comment]
I want to note I've experienced both normal behavior and this aberrant behavior on the same browser, same computer, same plugins. Seems very random

**Comment by KahasKahas** [comment]
I've tested a normal successful payment without reproducing this bug yet, with various adblock or forceful crashes.

A possible alternative solution would be to cross check the second badge form against the database to notify the user there is possibly already an order with that name being processed and ask them to check their emails before posting another one.

Would that make sense to you ?

**Comment by KahasKahas** [comment]
Also I have fixed a strange edge case where a payment is already successful,
and if the checkout page is still open and being refreshed it would crash (the incomplete order cannot be found because it's already completed).
In that scenario, the impossible checkout page tries to redirect to the review order page for this completed order instead.
